# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a4257e292eb446700b35d35e8ab0f8b25cf66153557736ae7f47c35a662eb8276878598a1c229e04da8b88770559cd1f1d136e03f7ca8da6c8ba3d449552c99e

test:
  secret_key_base: 9d2ef27caf267fda31f17b6e11c3ce414ad24263e65cc8fb09aa6c7e9b9606466c270410f43de3eea2035cf17023bc3d353c0f424582aa8fae0b7c17a59d90c1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
